#include "voxel.hpp"
#include <fstream>
#include <stdexcept>

VoxelStats writeVoxelOBJ(const std::vector<const Octree*>& leaves,
                          const std::string& outputPath) {
    std::ofstream out(outputPath);
    if (!out.is_open())
        throw std::runtime_error("Cannot write output file: " + outputPath);

    out << "# Voxelized output generated by octree-voxelizer\n";

    int vertOffset = 1; // OBJ indices are 1-based
    int totalVerts = 0;
    int totalFaces = 0;
    int numVoxels  = (int)leaves.size();

    for (const Octree* leaf : leaves) {
        const Vec3& lo = leaf->minBound;
        const Vec3& hi = leaf->maxBound;

        // 8 corners of the box
        // Order: (lo.x, lo.y, lo.z) ... (hi.x, hi.y, hi.z)
        //   v0 = lo
        //   v1 = hi.x, lo.y, lo.z
        //   v2 = hi.x, hi.y, lo.z
        //   v3 = lo.x, hi.y, lo.z
        //   v4 = lo.x, lo.y, hi.z
        //   v5 = hi.x, lo.y, hi.z
        //   v6 = hi.x, hi.y, hi.z
        //   v7 = lo.x, hi.y, hi.z
        out << "v " << lo.x << " " << lo.y << " " << lo.z << "\n"; // v0
        out << "v " << hi.x << " " << lo.y << " " << lo.z << "\n"; // v1
        out << "v " << hi.x << " " << hi.y << " " << lo.z << "\n"; // v2
        out << "v " << lo.x << " " << hi.y << " " << lo.z << "\n"; // v3
        out << "v " << lo.x << " " << lo.y << " " << hi.z << "\n"; // v4
        out << "v " << hi.x << " " << lo.y << " " << hi.z << "\n"; // v5
        out << "v " << hi.x << " " << hi.y << " " << hi.z << "\n"; // v6
        out << "v " << lo.x << " " << hi.y << " " << hi.z << "\n"; // v7

        int b = vertOffset; // base index (1-based)

        // 6 faces, each split into 2 triangles (12 faces total per voxel)
        // Front  (-Z): v0 v3 v2 v1
        out << "f " << b+0 << " " << b+3 << " " << b+2 << "\n";
        out << "f " << b+0 << " " << b+2 << " " << b+1 << "\n";
        // Back   (+Z): v4 v5 v6 v7
        out << "f " << b+4 << " " << b+5 << " " << b+6 << "\n";
        out << "f " << b+4 << " " << b+6 << " " << b+7 << "\n";
        // Left   (-X): v0 v4 v7 v3
        out << "f " << b+0 << " " << b+4 << " " << b+7 << "\n";
        out << "f " << b+0 << " " << b+7 << " " << b+3 << "\n";
        // Right  (+X): v1 v2 v6 v5
        out << "f " << b+1 << " " << b+2 << " " << b+6 << "\n";
        out << "f " << b+1 << " " << b+6 << " " << b+5 << "\n";
        // Bottom (-Y): v0 v1 v5 v4
        out << "f " << b+0 << " " << b+1 << " " << b+5 << "\n";
        out << "f " << b+0 << " " << b+5 << " " << b+4 << "\n";
        // Top    (+Y): v3 v7 v6 v2
        out << "f " << b+3 << " " << b+7 << " " << b+6 << "\n";
        out << "f " << b+3 << " " << b+6 << " " << b+2 << "\n";

        vertOffset += 8;
        totalVerts += 8;
        totalFaces += 12;
    }

    return { numVoxels, totalVerts, totalFaces };
}
